# Traefik v3 static configuration

[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "ERROR" # DEBUG, INFO, WARN, ERROR, FATAL, PANIC

[accessLog]
  filePath = "/var/log/traefik/access.log"
  format = "json"

# Traefik dashboard
[api]
  dashboard = true

# Entry points
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      certResolver = "cloudflare"
      options = "default"
  [entryPoints.monitor]
    address = ":8081"

# Dynamic configuration provider (file-based)
[providers.file]
  watch = true
  filename = "/etc/traefik/rules.toml"

# Docker provider
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  network = "traefik_proxy"
  watch = true
  # Only expose containers with traefik.enable=true label
  exposedByDefault = false

# Let's Encrypt / ACME via Cloudflare DNS challenge
[certificatesResolvers.cloudflare.acme]
  email = "email@domain.com" # any email id will work
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.cloudflare.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 300
  [[certificatesResolvers.cloudflare.acme.domains]]
    main = "example.com"
    sans = ["*.example.com"]

